#### collections

In [1]:
[2,2,2]

3-element Array{Int64,1}:
 2
 2
 2

In [9]:
a = [[1, 2, 3] [4, 5, 6]]
b = [1, 2, 3]
a * b

LoadError: DimensionMismatch("matrix A has dimensions (3,2), vector B has length 3")

In [10]:
repmat([1, 2], 3)

6-element Array{Int64,1}:
 1
 2
 1
 2
 1
 2

In [11]:
typeof(("A", 3, "B", 4, "C", 2))

Tuple{String,Int64,String,Int64,String,Int64}

#### dataframes

In [1]:
using DataFrames

In [6]:
df3 = DataFrame()
df3[:A] = rand(15)
df3[:B] = rand(15)
df3[:C] = rand(15)
df3[:D] = rand(15);

In [7]:
df3

15×4 DataFrames.DataFrame
│ Row │ A          │ B         │ C         │ D         │
├─────┼────────────┼───────────┼───────────┼───────────┤
│ 1   │ 0.00814664 │ 0.076879  │ 0.48874   │ 0.279595  │
│ 2   │ 0.553837   │ 0.349782  │ 0.0493033 │ 0.0316861 │
│ 3   │ 0.112574   │ 0.477234  │ 0.50342   │ 0.205869  │
│ 4   │ 0.595797   │ 0.73844   │ 0.143354  │ 0.680536  │
│ 5   │ 0.188906   │ 0.494736  │ 0.610357  │ 0.451324  │
│ 6   │ 0.721617   │ 0.61728   │ 0.217796  │ 0.618925  │
│ 7   │ 0.6805     │ 0.0740884 │ 0.12758   │ 0.308968  │
│ 8   │ 0.793292   │ 0.254219  │ 0.459652  │ 0.812022  │
│ 9   │ 0.0377718  │ 0.289241  │ 0.0683935 │ 0.0855456 │
│ 10  │ 0.423273   │ 0.281706  │ 0.139072  │ 0.789013  │
│ 11  │ 0.494859   │ 0.230787  │ 0.706603  │ 0.925335  │
│ 12  │ 0.408847   │ 0.38374   │ 0.850975  │ 0.385229  │
│ 13  │ 0.320924   │ 0.769739  │ 0.999747  │ 0.889282  │
│ 14  │ 0.252764   │ 0.0737813 │ 0.0304905 │ 0.602408  │
│ 15  │ 0.526959   │ 0.443998  │ 0.497063  │ 0.639177  │

In [8]:
deleterows!(df3, [3,5,9])

12×4 DataFrames.DataFrame
│ Row │ A          │ B         │ C         │ D         │
├─────┼────────────┼───────────┼───────────┼───────────┤
│ 1   │ 0.00814664 │ 0.076879  │ 0.48874   │ 0.279595  │
│ 2   │ 0.553837   │ 0.349782  │ 0.0493033 │ 0.0316861 │
│ 3   │ 0.595797   │ 0.73844   │ 0.143354  │ 0.680536  │
│ 4   │ 0.721617   │ 0.61728   │ 0.217796  │ 0.618925  │
│ 5   │ 0.6805     │ 0.0740884 │ 0.12758   │ 0.308968  │
│ 6   │ 0.793292   │ 0.254219  │ 0.459652  │ 0.812022  │
│ 7   │ 0.423273   │ 0.281706  │ 0.139072  │ 0.789013  │
│ 8   │ 0.494859   │ 0.230787  │ 0.706603  │ 0.925335  │
│ 9   │ 0.408847   │ 0.38374   │ 0.850975  │ 0.385229  │
│ 10  │ 0.320924   │ 0.769739  │ 0.999747  │ 0.889282  │
│ 11  │ 0.252764   │ 0.0737813 │ 0.0304905 │ 0.602408  │
│ 12  │ 0.526959   │ 0.443998  │ 0.497063  │ 0.639177  │

#### extra packages

In [5]:
using Distributions

In [18]:
x = rand(Normal(80, 10), 20000)
var(x)

98.51206269952795

In [19]:
?randn

search: randn randn! sprandn randstring ZeroMeanDiagNormal



```
randn([rng=GLOBAL_RNG], [T=Float64], [dims...])
```

Generate a normally-distributed random number of type `T` with mean 0 and standard deviation 1. Optionally generate an array of normally-distributed random numbers. The `Base` module currently provides an implementation for the types [`Float16`](@ref), [`Float32`](@ref), and [`Float64`](@ref) (the default).

# Examples

```jldoctest
julia> rng = MersenneTwister(1234);

julia> randn(rng, Float64)
0.8673472019512456

julia> randn(rng, Float32, (2, 4))
2×4 Array{Float32,2}:
 -0.901744  -0.902914  2.21188   -0.271735
 -0.494479   0.864401  0.532813   0.502334
```


In [21]:
?TDist

search: TDist MvTDist DiscreteDistribution MatrixDistribution



```
TDist(ν)
```

The *Students T distribution* with `ν` degrees of freedom has probability density function

$$
f(x; d) = \frac{1}{\sqrt{d} B(1/2, d/2)}
\left( 1 + \frac{x^2}{d} \right)^{-\frac{d + 1}{2}}
$$

```julia
TDist(d)      # t-distribution with d degrees of freedom

params(d)     # Get the parameters, i.e. (d,)
dof(d)        # Get the degrees of freedom, i.e. d
```

External links

[Student's T distribution on Wikipedia](https://en.wikipedia.org/wiki/Student%27s_t-distribution)


In [23]:
using HypothesisTests

In [24]:
?EqualVarianceTTest

search: EqualVarianceTTest UnequalVarianceTTest EqualVarianceZTest



```
EqualVarianceTTest(x::AbstractVector{T<:Real}, y::AbstractVector{T<:Real})
```

Perform a two-sample t-test of the null hypothesis that `x` and `y` come from distributions with equal means and variances against the alternative hypothesis that the distributions have different means but equal variances.

Implements: [`pvalue`](@ref), [`confint`](@ref)
